### PR TITLE
Fix a typo and turn URLs into clickable links

### PR DESCRIPTION
**Pull request by ur5us**

### CODE REVIEW

**Comment by ur5us** [comment]
@mansona Is contributing to this little app useful?

**Review by mansona — APPROVED** [review]
🎉 thanks for the contribution!

**Comment by mansona** [comment]
@ur5us and yes contributions are always useful 🎉 😂

**Comment by ur5us** [comment]
@mansona 2 questions:

1. Should I go on and probably upgrade deps, in particular Ember itself?
2. Would this qualify for Hacktoberfest?

**Comment by mansona** [comment]
@ur5us so I said that contributions are always useful, but I guess some are less worth putting your time into 🤔  This repository will likely not be used again until the next Contributor Workshop, so it won't be as useful to update this for probably a year. If you haven't already done any work on it I would not spend any time updating it

**Comment by mansona** [comment]
and as for hacktoberfest... I think all I needed to do is add the `hacktoberfest-accepted` label, so let me know if that shows up 👍

**Pull request merged**
